# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  aiaapi:
    image: aiaapi
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    ports:
      - 5264:80
