using System.Text.RegularExpressions;

namespace aia_api.Application.Helpers;

public class CommentManipulationHelper
{
    private readonly ILogger<CommentManipulationHelper> _logger;
    private const string FindCommentsRegex =
        @"[^\S\r\n]*((?<=\s|^)\/\/[^\n]*|\/\*(?:(?!\*\/)[\s\S])*\*\/|\/\*\*(?:(?!\*\/)[\s\S])*\*\/)\n*";

    public CommentManipulationHelper(ILogger<CommentManipulationHelper> logger)
    {
        _logger = logger;
    }

    public string ReplaceCommentsInCode(string generatedComment, string inputCode)
    {
        MatchCollection commentMatches = GetComments(generatedComment, @"\[RETURN\](.*?)\[\/RETURN\]");

        if (commentMatches.Count <= 0)
        {
            _logger.LogInformation("No blocks of [RETURN][/RETURN] found in the LLM response, skipping comment replacement for file.");
            return inputCode;
        }

        string updatedCode = inputCode;
        foreach (Match match in commentMatches)
        {
            string comment = match.Groups[1].Value.Trim(Environment.NewLine.ToCharArray());
            string methodSignature = Regex.Replace(comment, FindCommentsRegex, "");
            _logger.LogDebug("Generated comment:\n{comment}", comment);
            
            updatedCode = ReplaceComment(comment, methodSignature, updatedCode);
        }

        _logger.LogDebug("Updated code with comments:\n{updatedCode}", updatedCode);
        return updatedCode;
    }
    
    /// <summary>
    /// Replaces existing comments in the code with comments generated by the LLM.
    /// </summary>
    /// <param name="comment">The comment to replace the existing comments with.</param>
    /// <param name="methodSignature">The signature of the method to replace comments for.</param>
    /// <param name="code">The input code containing the comments to replace.</param>
    /// <returns>The input code with the comments replaced by the specific comment pattern.</returns>
    private string ReplaceComment(string comment, string methodSignature, string code)
    {
        string specificCommentPattern = FindCommentsRegex;
        foreach (string signatureLine in methodSignature.Split(Environment.NewLine))
        {
            specificCommentPattern += $@"\s*{Regex.Escape(signatureLine)}";
        }

        Match match = Regex.Match(code, specificCommentPattern);
        if (!match.Success)
        {
            _logger.LogDebug("Could not find comment, possibly because the LLM changed some code:\n{comment}", comment);
            return code;
        }
        
        string updatedCommentWithFormatting = ApplyFormatting(match, comment);
        return Regex.Replace(code, Regex.Escape(match.Value), updatedCommentWithFormatting);
    }

    private string ApplyFormatting(Match match, string comment)
    {
        string inputCommentFormatting = GetCommentFormatting(match.Value);
        return string.Join(Environment.NewLine, comment.Split(Environment.NewLine)
            .Select(line => inputCommentFormatting + line));
    }
    
    private string GetCommentFormatting(string commentLine)
    {
        int indentCount = commentLine.TakeWhile(c => c is ' ' or '\t').Count();
        return new string(' ', indentCount);
    }

    private MatchCollection GetComments(string content, string pattern)
    {
        return Regex.Matches(content, pattern, RegexOptions.Singleline);
    }
}